version: "3.8"
services:
  willard-logs:
    container_name: willard-logs
    ports:
      - "3335:3335"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - SESSION_SECRET=${SESSION_SECRET}
      - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
      - PORT=${PORT}
      - SSL=${SSL}
      - SSL_CERT=${SSL_CERT}
      - SSL_KEY=${SSL_KEY}
      - DATABASE=${DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
      - ADMIN_MOD=${ADMIN_MOD}
      - STEAM_KEY=${STEAM_KEY}
      - ALLOWED_RANKS=${ALLOWED_RANKS}
    hostname: logs.willard.local
    network_mode: "bridge"