version: "3.3"
services:
  willard-logs:
    container_name: willard-ss-logs
    ports:
      - "3336:3336"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - SESSION_SECRET=${SESSION_SECRET}
      - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
      - PORT=${PORT}
      - SSL=${SSL}
      - SSL_CERT=${SSL_CERT}
      - SSL_KEY=${SSL_KEY}
      - DATABASE=${DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
      - ADMIN_MOD=${ADMIN_MOD}
      - STEAM_KEY=${STEAM_KEY}
      - ALLOWED_RANKS=${ALLOWED_RANKS}
    hostname: sslogs.willard.local
    network_mode: "bridge"
    healthcheck:
      test: ["CMD", "curl", "http://sslogs.willard.local:3336"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s