version: "3.8"

networks:
  logs-network:
    driver: bridge

services:
  willard-logs:
    container_name: willard-logs
    ports:
      - "3335:3335"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - SESSION_SECRET=${SESSION_SECRET}
      - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
      - PORT=${PORT}
      - SSL=${SSL}
      - SSL_CERT=${SSL_CERT}
      - SSL_KEY=${SSL_KEY}
      - DATABASE=${DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
      - ADMIN_MOD=${ADMIN_MOD}
      - STEAM_KEY=${STEAM_KEY}
      - ALLOWED_RANKS=${ALLOWED_RANKS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    hostname: logs.willard.local
    networks:
      - logs-network
    healthcheck:
      test: ["CMD", "curl", "http://logs.willard.local:3335"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: willard-logs-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - logs-network
    sysctls:
      - net.core.somaxconn=512
      - vm.overcommit_memory=1

volumes:
  redis-data:
